name: bazel

on:
  push:
    branches: [ master, npmrc ]
  pull_request:
    branches: [ master, npmrc ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 2.2.0

    - name: Build
      run: |
        bazel build //...
