name: yarn

on:
  push:
    branches: [ master, npmrc ]
  pull_request:
    branches: [ master, npmrc ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn install
      env:
        NPM_FA_TOKEN: ${{ secrets.NPM_FA_TOKEN }}
